### ISSUE TITLE
Use native system fonts

### ISSUE THREAD

**Issue by cheeaun** [zz85/space-radar#14]
On Mac, use San Francisco for newer OS with fallback Helvetica Neue. On Windows, Segoe UI. And so on for other OS.

Relevant articles:

- http://furbo.org/2015/07/09/i-left-my-system-fonts-in-san-francisco/
- https://medium.com/@mwichary/system-shock-6b1dc6d6596f

**Comment by zz85** [comment]
nice links Chee Aun! would you happen to know of any examples that has implemented this well? Now that I'm also using Photon, I'm not sure how well this goes with the windows build too..

**Comment by cheeaun** [comment]
One example would be https://medium.com/ (some text uses system while some uses Serif). My app http://cheeaun.github.io/hackerweb/ is already embracing this and haven't seen any issues.

Here's also a more recent article http://www.smashingmagazine.com/2015/11/using-system-ui-fonts-practical-guide/
