### ISSUE TITLE
Blank window

### ISSUE THREAD

**Issue by webdrone** [zz85/space-radar#18]
Space radar starts scanning my disk and periodically refreshing the on-screen image while saying "Scanning, try grabbing a drink". When done, everything disappears and I'm faced with a blank window, only the window controls (close, minimise, maximise) show.

Mac OS X 10.11.3
256GB SSD

**Comment by zz85** [comment]
Hi @webdrone, sorry for the late reply. May I know whether you're using the binary builds and which version? If you're using the developer's version, is there any messages in the console?

**Comment by webdrone** [comment]
No worries — I’m using the version on brew cask, which is 4.4.0, not dev edition.

**Comment by thejmazz** [comment]
+1, same issue, OSX 10.11.1, 256GB. v4.4.0 from github releases

**Comment by zz85** [comment]
Oh, I didn't know Evan wrote a space visualization app too.

Hmm. I'm not too sure how I can narrow this blank window problem. I'm not sure if it is caused by some memory limits. Anyways, have you all tried scanning a folder (instead of the entire drive)? Does it work in 4.4.0?

**Comment by thejmazz** [comment]
Hey Joshua, I had the problem with *scanning a folder* in 4.40 **and** 3.3.0 unfortunately. However, it seems to only happen sometimes, but perhaps a bit more common in 4.4.0.

Sorry I do not have the time to narrow down when it happens for myself - It worked at some point and I have cleaned up my drive so probably won't be using it for a little while now.
