### ISSUE TITLE
Text on top of text when trying to scan disk after having scanned memory

### ISSUE THREAD

**Issue by dbkaplun** [zz85/space-radar#24]
![screen shot 2016-11-04 at 10 27 06 am](https://cloud.githubusercontent.com/assets/1765130/20015715/c18bb314-a279-11e6-935a-1399f373b0af.png)
![screen shot 2016-11-04 at 10 27 40 am](https://cloud.githubusercontent.com/assets/1765130/20015717/c3950f98-a279-11e6-8dd5-347bfe8471bc.png)

**Comment by zz85** [comment]
This should be fixed in v5. https://github.com/zz85/space-radar/releases/tag/v5.1.0
