### ISSUE TITLE
Release 4.4.0 is only for Mac OS

### ISSUE THREAD

**Issue by Chris2011** [zz85/space-radar#26]
I wanted to try the tool but vesion 4.4.0 is not for Windows. Only for mac. Version 3.3.0 is vor Windows.
Please make it available for Windows too.

Thx

**Comment by zz85** [comment]
Please find new windows builds here https://github.com/zz85/space-radar/releases

Thanks!

**Comment by Chris2011** [comment]
Great it works, thx.
