### ISSUE TITLE
Windows feedback

### ISSUE THREAD

**Issue by tterb** [zz85/space-radar#28]
First off, I want to say that I really like the UI, it's actually pretty similar to the disk scanner tool I currently use. So when I found this project and saw in the README that you were looking for feedback from Windows users, I thought I'd give you my first impressions.  
*Note this analysis only pertains to v3.3.0, as there currently isn't a windows version of the pre-release .* 
  *  As you can see in the screenshot below, the text that is supposed to be in the middle is a little off-centered.
  * When compared to the images in the README, it also seems like the graph colors are appearing differently.
  *  To analyze my whole root directory the program took about 3.5 minutes, which is a bit slow, but it appears that you plan to address performance issues in an upcoming release. 
  * I would prefer if the program could also display the remaining empty portion of the drive as a part of the graph.
  * It would also be nice to have the graph scale with the size of its containing window, because when I first launched the application the window only displayed about 80% of the overall graph and needed to be adjusted. 

![2017-04-15_02h04_26](https://cloud.githubusercontent.com/assets/16360374/25062368/e9df5db8-217f-11e7-9302-ef01906456a8.png)

Overall, I think this project has a lot of potential, so feel free to let me know if any of my points need clarification or you need someone to test future builds. 👍

**Comment by zz85** [comment]
Hi @JonSn0w, updated windows builds is now available on https://github.com/zz85/space-radar/releases/tag/v5.1.0
