### ISSUE TITLE
Permission Denied (publickey)

### ISSUE THREAD

**Issue by Gander7** [zz85/space-radar#29]
I'm pretty this is my issue but after looking through readme and release notes I'm nost sure how to resolve it and I'm using Windows 10 64x Home Edition.
I downloaded, unzipped and ran npm install on space-radar-4.4.0.zip.
During the npm install I received this error:
` Cloning into bare repository 'path\git-github-com-experiments-photon-git-{guid}`
` Warning: Permanently add 'github, {IP}' (RSA) to the list of known hosts`
` Permission denied (publickey)`
` fatal: Could not read from remote repository.`
` Please make sure you have the correct access rights`
` and the repository exists.`

**Comment by cheeaun** [comment]
Perhaps need to change the `dependencies` for `photon` in `package.json` to `https://github.com/connors/photon.git`

> https://github.com/zz85/space-radar/blob/54d537347217092e0f1d16cfb81e360c2774c94f/package.json#L34
