### ISSUE TITLE
How to read a size.txt(.gz) file?

### ISSUE THREAD

**Issue by FxIII** [zz85/space-radar#30]
I'm not able to open a size file from the UI.
Did I miss something macroscopic?

**Comment by jsundram** [comment]
+1

**Comment by joerg** [comment]
There has not been a release in a while and this specific feature is not included in the latest build.

**Comment by zz85** [comment]
One of the new builds from https://github.com/zz85/space-radar/releases should work. Let me know if it doesn't!
