### ISSUE TITLE
space-radar slow/unresponsive with large text input

### ISSUE THREAD

**Issue by jsundram** [zz85/space-radar#31]
I have a textfile input with ~330K entries; I've let space-radar run for several hours, but it doesn't seem to be doing anything.

**Comment by zz85** [comment]
are you able to post this textfile somewhere (textbin or something) so I can see what the errors are?

**Comment by jsundram** [comment]
Sure, here's the gzip file I created (format: file size in bytes, followed by tab, followed by filename):
[sizes_hashed.txt.gz](https://github.com/zz85/space-radar/files/1275545/sizes_hashed.txt.gz)

**Comment by zz85** [comment]
thanks for the test file, i'm able to reproduce an issue with this. will be make a fix so it would render like

![image](https://user-images.githubusercontent.com/314997/30260857-5d5a6e1c-96fc-11e7-8efb-a19b690da197.png)

**Comment by zz85** [comment]
This should be fixed in master now. Let me know if you still encounter issues.

**Comment by jsundram** [comment]
this is awesome, thank you!

**Comment by eladcandroid** [comment]
Happened to me with the newest release...
