### ISSUE TITLE
open a directory

### ISSUE THREAD

**Issue by vanzandtj** [zz85/space-radar#33]
I'm using space-radar on a Mac.  When I right-click on a directory, the "open" option is grayed out.  I suggest that this menu option should work the same way as "open" on a command line - that it should launch Finder on the directory.  That's the interface most familiar to a new user.  (I suppose the corresponding tool under Windows would be the Windows Explorer).

I would also like the option to open a terminal window in the directory, since for an experienced user there are many actions that are easier from the command line.

**Comment by zz85** [comment]
May I know what version you're using? Right click > locate works for me (lastest from git repo).

**Comment by vanzandtj** [comment]
I don't see a version number.  I installed it yesterday with "brew cask
install spaceradar", so it's whatever version was last "brewed" or whatever.

Here's the content of info.plist:

$ less Info.plist


<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "
http://www.apple.com/DTDs/PropertyList-1.0.dtd">

<plist version="1.0">

  <dict>

    <key>BuildMachineOSBuild</key>

    <string>14F1021</string>

    <key>CFBundleDisplayName</key>

    <string>SpaceRadar</string>

    <key>CFBundleExecutable</key>

    <string>Electron</string>

    <key>CFBundleIconFile</key>

    <string>atom.icns</string>

    <key>CFBundleIdentifier</key>

    <string>com.electron.spaceradar</string>

    <key>CFBundleInfoDictionaryVersion</key>

    <string>6.0</string>

    <key>CFBundleName</key>

    <string>SpaceRadar</string>

    <key>CFBundlePackageType</key>

    <string>APPL</string>

    <key>CFBundleShortVersionString</key>

    <string>0.34.3</string>

    <key>CFBundleVersion</key>

    <string>0.34.3</string>

    <key>DTSDKBuild</key>

    <string>15A278</string>

    <key>DTSDKName</key>

    <string>macosx10.11</string>

    <key>DTXcode</key>

    <string>0710</string>

    <key>DTXcodeBuild</key>

    <string>7B91b</string>

    <key>LSApplicationCategoryType</key>

    <string>public.app-category.developer-tools</string>

    <key>LSMinimumSystemVersion</key>

    <string>10.8.0</string>

    <key>NSHighResolutionCapable</key>

    <true/>

    <key>NSMainNibFile</key>

    <string>MainMenu</string>

    <key>NSPrincipalClass</key>

    <string>AtomApplication</string>

    <key>NSSupportsAutomaticGraphicsSwitching</key>

    <true/>

    <key>CFBundleURLTypes</key>

**Comment by vanzandtj** [comment]
Ah - "locate" works for me too.  That's a misleading label, though.  It
ought to say "open in finder" or just "open".

And, yes, I'm reluctant to click on random links just to see what happens.
Especially when the specific label I'm looking for is actually there, but
grayed out.

**Comment by zz85** [comment]
This is addressed in #35. I'll be naming it "Open directory" and "Open file" to make things clearer.
